config/routes.rb
Rails.application.routes.draw do
    scope "(:locale)", locale: /en|vi/ do
      root "static_pages#home"
      get "/help", to: "static_pages#help"
      get "/about", to: "static_pages#about"
      get "/contact", to: "static_pages#contact"
      get "/signup", to: "users#new"
      post "/signup", to: "users#create"
      get "/login", to: "sessions#new"
      post "/login", to: "sessions#create"
      delete "/logout", to: "sessions#destroy"
      resources :users, only: %i(index new show create edit update)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  before_save{email.downcase!}
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true

  validates :name, presence: true,
                  length: {maximum: Settings.length.name}
  validates :email, presence: true,
                    length: {maximum: Settings.length.email},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: true
  validates :password, presence: true,
                      length: {minimum: Settings.length.password}

  has_secure_password

  def remember
    self.remember_token = User.new_token
    update_column :remember_token, User.digest(remember_token)
  end

  def authenticated? remember_token
    Bcrypt::Password.new(remember_digest).is_password? remember_token
  end

  def forget
    update_column :remember_digest, nil
  end

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    session_params = params[:session]
    user = User.find_by(email: session_params[:email].downcase)
    if user&.authenticate(session_params[:password])
      log_in user
      session_params[:remember_me] == Settings.check ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = t "pages.flash.invalid"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: %i(new create show)
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate page: params[:page]
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = t "pages.flash.danger"
    redirect_to login_url
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "pages.flash.success"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by params[:id]
    if @user.update user_params
      flash[:success] = t "pages.profile_updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    user = User.find_by id: params[:id]
    if user&.destroy
      flash[:success] = t "pages.flash.delete_user"
    else
      flash[:danger] = t "pages.flash.delete_fail"
    end
    redirect_to users_url
  end

  private

  def user_params
    params
      .require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = t "pages.flash.please_login"
    redirect_to login_url
  end

  def correct_user
    @user = User.find_by(id: params[:id])
    return if @user == current_user

    flash[:danger] = t "pages.edit.Wrong_user"
    redirect_to(root_url)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t("pages.home.base_title")
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user&.authenticated? cookies[:remember_token]
        log_in user
        @current_user = user
      end
    end
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: Settings.size.digit_80}
    size = options[:size]
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <%= t "pages.footer.footer_html"%>
  <nav>
    <ul>
    <li><%= link_to t("pages.nav.about"), about_path %></li>
    <li><%= link_to t("pages.footer.contact"), contact_path %></li>
    <li><a href="https://news.railstutorial.org/"><%= t"pages.footer.news" %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

<div class="container">
  <%= link_to t("pages.nav.sample_app"), root_path , id: "logo" %>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to t("pages.nav.home"), root_path %></li>
      <li><%= link_to t("pages.nav.help"), help_path %></li>
      <% if logged_in? %>
          <li><%= link_to t("pages.nav.user"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              <%= t "pages.nav.account" %><b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("pages.nav.profile"), current_user %></li>
              <li><%= link_to t("pages.nav.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("pages.nav.log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("pages.nav.log_in"), login_path %></li>
        <% end %>
  </ul>
  </nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <li><%= link_to t("pages.nav.eng"), locale: :en %></li>
    <li><%= link_to t("pages.nav.vie"), locale: :vi %></li>
  </head>
  <body>
    <%=render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%=render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    <%= t "pages.form.contains_error", count: @user.errors.count %>
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, t("pages.nav.about") %>
<h1><%= t "pages.nav.about" %> </h1>
<%= t "pages.about.about_html" %>

app/views/static_pages/contact.html.erb
<% provide :title , t("pages.footer.contact") %>
<h1><%= t "pages.footer.contact" %> </h1>
<%= t "pages.contact.contact_html" %>

app/views/static_pages/help.html.erb
<% provide :title , t("pages.nav.help") %>
<h1><%= t "pages.nav.help" %> </h1>
<%= t "pages.help.help_html" %>

app/views/static_pages/home.html.erb
<% provide :title, t("pages.nav.home") %>
<div class="center jumbotron">
<h1><%= t "pages.home.welcome" %> </h1>
<%= t "pages.about.about_html" %>
<%= link_to t("pages.home.sign_up_now"), signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages" %>
  <%= f.label :name, t("pages.form.name") %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :password, t("pages.form.password")%>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation, t("pages.form.password_confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.length.digit_50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
|   <%= link_to t("pages.user.delete"), user, method: :delete, data: {confirm: t("pages.user.alert")} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide:title, t("pages.edit.title") %>
<% provide:button_text, t("pages.form.save_changes") %>
<h1><%= t "pages.edit.update_profile" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t("pages.edit.change"),"https://gravatar.com/emails", target: "_blank" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("pages.nav.all_users") %>
<h1><%= t "pages.nav.all_users" %></h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t("pages.home.sign_up") %>
<% provide :button_text, t("pages.form.create_account") %>
<h1><%= t "pages.home.sign_up" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="container">
  <aside class="row">
    <section>
      <div class="col-sm-2">
        <%= gravatar_for @user %>
      </div>
      <div class="col">
        <h1>
          <%= @user.name %>
        </h1>
        <h1>
          <%= @user.email %>
        </h1>
      </div>
    </section>
  </aside>
</div>